### ISSUE TITLE
Autoscaling Develop properties file shoulb be renamed

### ISSUE THREAD

**Issue by loic35** [openbaton/autoscaling-engine#2]
The file committed and the start script use the name : ase.properties; the release uses openbaton-ase.properties.

The last one should be used.

**Comment by wittling** [comment]
When you download the full packaged distribution, there is a lot more than just the properties that is different. The full packaged distributions include a framework in /usr/lib/openbaton directory. This directory contains an env folder that contains a script that sets up the environment prior to launch, a SystemD unit file, a lib directory for the jar file, and so on.

What I typically do is build the component out of git, and then copy the jar into the /usr/lib/openbaton/ase directory, and adjust the env script and, if necessary, the unit file. I also rename the properties file to the openbaton-[component] name so that they all look consistent.

Also worth mentioning is that the systemd scripts are not, by default, deployed in /etc/systemd/system/ path, but the /usr/lib/systemd directory (backwards compatibility to initd). Since I don't like my services run as initd (I run on CentOS not Ubuntu btw), I personally "port" them to the newer systemd services framework and put them in /etc/systemd/system (when you run systemctl daemon-reload) it will put them in the proper "wants" directory (i.e. multiuser-wants).

Maybe this is helpful. I find the framework useful so I don't have to start all of the services by hand and in order every time the OpenBaton VM is rebooted.
